### ISSUE TITLE
Обсуждение проекта

### ISSUE THREAD

**Issue by 0sektor0** [frontend-park-mail-ru/2018_2___proto__#23]

**Comment by 0sektor0** [comment]
С чем сегодня определились

1. Все взаимодействие с серваком происходит через API (пользователь отправляет JSON файл и сервак отвечает ему JSON файлом)

2. Пользователь при каждом запросе к серваку в JSON'e передает JWT токен

3. Примеры ответов сервера
{
	"status": true,
	"token": "sadasd123nmnm321312m3n1m23nm123nm12n3m",
	"user": 
	{
		"name": "asd",
		"password": "asdasd" 
	}
	"characters": [
		{
			...
		},
		{
			...
		}
	]	
}
{
	"status": false,
	"error": 
	{
		"code": 123,
		"message": "invalid password or login"
	}
}

4. Пример запросов пользователя
{
	"token": "asdasdasdasdasd"
}

5. Дополнительные экраны:
	1) Страница выбора персонажа
	2) Страница инфы о персонаже
	3) Страница старата поиска игра (2 кнопки Singleplayer, Multiplayer)
	4) Экран пользователя
	5) Экран игры

6. Экарн игры выглядит следующим образом: вид сбоку, стоят 2 персонажа друг напротив друга, внизу экрана полоска скиллов, вверху экрана хп и счетчик ходов (должно выглядит примерно так, как в Darkest Dungeon)

7. Во время игры, персонажи стоят и воспроизводят дефолтную анимацию, после хода 'вылетает экран' в котором воспроизводится анимация атаки 

8. Типы вопросов:
	1) Вопрос с выбором варианта ()
	2) Вопрос, где нужно ввести число (правильно отвечает тот, кто ввел число ближе к настоящему ответу)

**Comment by mouseartiom** [comment]
4.2: наверное  лучше сделать слайдер с текстовым окошком в этом месте, это изящнее и удобнее на мобилках.

**Comment by Armelior** [comment]
Для этого есть дизайн-документ.
