### ISSUE TITLE
Написать сервер раздающий макеты 

### ISSUE THREAD

**Issue by 0sektor0** [frontend-park-mail-ru/2018_2___proto__#3]

**Comment by 8coon** [comment]
Оставь пожалуйста ссылку на пулл реквест

**Comment by 0sektor0** [comment]
Создать отдельную ветку от мастера (hw-master) и туда уже пуллить или сразу в мастер?

**Comment by 8coon** [comment]
Я думаю, можно сразу в мастер

**Comment by 0sektor0** [comment]
https://github.com/frontend-park-mail-ru/2018_2___proto__/pull/9
